### ISSUE TITLE
Pass an ILogger implementation to API calls

### ISSUE THREAD

**Issue by AlexJitianu** [rmraya/Fluenta#1]
Hello,

We are currently building an Oxygen XML Editor plugin that integrates Fluenta into the DITA Maps Manager. We are using {{com.maxprograms.fluenta.API}} for calling Fluenta operations. I've noticed that there is a {{com.maxprograms.tmengine.ILogger}} interface for notifying progress. 
{{com.maxprograms.fluenta.API}} uses a {{com.maxprograms.utils.SimpleLogger}} that prints progress to console. It would be great if we could pass our own {{ILogger}} implementation.

**Comment by rmraya** [comment]
An option to pass your own logger can be added, that's OK. 
Submit a pull request if you have the code.

**Comment by rmraya** [comment]
Code has changed a lot for release 3.0. Create a pull request if you want additional changes.
