### ISSUE TITLE
After importing an xliff file I get a bunch of "*.skl" files created next to it

### ISSUE THREAD

**Issue by raducoravu** [rmraya/Fluenta#10]
I import an Xliff file to a DITA Map, Fluenta properly creates the DITA Map with topics in the target folder but after the import I also have a bunch of files "*.skl" next to the xliff. Maybe the import could delete those files as well?

**Comment by rmraya** [comment]
Fluenta should not leave skeletons in the target folder after importing XLIFF. That would be a program error.

I have not seen that behavior in Fluenta so far. Please provide indications that I could use to reproduce the problem and fix the issue.

**Comment by raducoravu** [comment]
We double checked, we can reproduce this with the 3.3.0 Fluenta release on which our Oxygen Fluenta add-on is based. But not with the 3.6.0 Fluenta library. So I guess we need to update our add-on for this.
