### ISSUE TITLE
Error generating XLiff for DITA Map

### ISSUE THREAD

**Issue by raducoravu** [rmraya/Fluenta#14]
I'm using a local build I made with the latest code in the Fluenta GitHub repo, running the xliff generation from the command line.
I have this public Oxygen XML Blog project which can be used for tests:

https://github.com/oxygenxml/blog

I create a project for "oxygen_xml_blog.ditamap", then attempt to create an xliff for translation to fr or es, I get two similar errors reported like this one:

    SEVERE: Error converting DITA Map
    org.xml.sax.SAXException: Error 'Error '/Users/.../Fluenta-main/map.dtd (No such file or directory)' in file:      '/Users/.../blog/topics/dp/specializations.ditamap'' in file: '/Users/.../blog/maps/dita-articles.ditamap'
	at openxliff/com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)
	at openxliff/com.maxprograms.converters.ditamap.DitaParser.recurse(Unknown Source)

and I'm not sure why, the dita-articles.ditamap is a plain DITA Map, I'm not sure why Fluenta does not resolve the public ID through the XML catalog and instead goes after the system ID.

**Comment by rmraya** [comment]
You have a file with this `PUBLIC` declaration: `"-//OASIS//DTD DITA 2.x Map//EN"`. That public identifier does not correspond to an official DITA release.

**Comment by raducoravu** [comment]
Thanks @rmraya, I had not noticed that. I switched back to using the DITA 1.3 DTDs. The DITA Open Toolkit already ships XML catalogs for the DITA 2.x DTDs maybe you could always attempt to use for resolution the latest XML catalogs shipped with the DITA OT.

**Comment by rmraya** [comment]
I only work with official DITA grammars published at OASIS.
