### ISSUE TITLE
XLiff generation does not finish on very large DITA Map

### ISSUE THREAD

**Issue by raducoravu** [rmraya/Fluenta#15]
I'm running on Mac OS a command line with the latest compiled Fluenta project.
Using this public Oxygen XML User's guide repo:
https://github.com/oxygenxml/userguide
attempting to create an xliff from this DITA Map:
https://github.com/oxygenxml/userguide/blob/master/DITA/UserManual.ditamap

I get a lot of warnings in the console like:

      WARNING: Undefined key for @keyref

but the export xliff process never really ends.
The DITA Map is valid in itself, it is complex, it may have duplicate keys because it uses ditaval filters to produce about 15 usermanuals from the same dita map so also the warnings that I receive in the console in my opinion are not correct.

I also tried to redirect the output to a log file like:

     sh fluenta_cli.sh -generateXLIFF abc.json > log3.txt

but I was not able to, the log file remains empty.

**Comment by rmraya** [comment]
The official release of Fluenta from [https://www.maxprograms.com/products/fluenta.html](https://www.maxprograms.com/products/fluenta.html) handles your User Guide without problems. I just used it to generate XLIFF 2.0 from your files on a Mac.

**Comment by raducoravu** [comment]
@rmraya thanks for testing this, maybe somehow the command line approached the Java memory limit (but without Xmx specified that would be 1/4 of the 16GBs I have on the Mac, so plenty of memory) or I did not have enough patience to wait for it.
