### ISSUE TITLE
API calls are missing the initializations performed in com.maxprograms.fluenta.Fluenta

### ISSUE THREAD

**Issue by AlexJitianu** [rmraya/Fluenta#2]
We are currently building an Oxygen XML Editor plugin that integrates Fluenta into the DITA Maps Manager. We are using `com.maxprograms.fluenta.API` for calling Fluenta operations.

In `com.maxprograms.fluenta.Fluenta` there are some initializations that take place:
- `checkConfigurations();`
- `System.setProperty("user.dir", Preferences.getPreferencesDir().getAbsolutePath());`

Right now one needs to manually perform these before calling `com.maxprograms.fluenta.API`. Some ideas, not sure if the right ones:

1. Perhaps add a new `com.maxprograms.fluenta.API.checkConfigurations(File resourcesDir)`. This `resourcesDir` would be the folder where the 'catalog', 'xmlfilter' folders are located. In our case, these resources are not located in _"user.dir"_, but in a specific folder inside the plugin.
2. Some resources are searched for inside "user.dir" and I guess that's why `System.setProperty("user.dir", Preferences.getPreferencesDir().getAbsolutePath());` gets called early on. In our case, Fluenta runs in the context of a larger application we are reluctant to change the _"user.dir"_ property as we are unsure of the implications. For example, in `Xml2Xliff.getIniFile()`, "xmlfilter" is looked for inside "OpenXLIFF_HOME" or "user.dir". In our case, it would help if Fluenta would use a custom system property as well, one that we can set before calling the API, for example "fluenta.home.dir".

**Comment by rmraya** [comment]
That's being changed in current private branch. An option for changing projects and memories folder is being added. Data location will be stored in a JSON file

**Comment by rmraya** [comment]
Code changed substantially for release 3.0
