### ISSUE TITLE
Remove the {{org.eclipse.swt}} dependency from the com.maxprograms.fluenta.API

### ISSUE THREAD

**Issue by AlexSmarandache15** [rmraya/Fluenta#3]
We are currently building an Oxygen XML Editor plugin that integrates Fluenta into the DITA Maps Manager. We are using com.maxprograms.fluenta.API for calling Fluenta operations.

For com.maxprograms.fluenta.API.generateXLIFF method, it is used com.maxprograms.fluenta.controllers.LocalController and certain static methods are used on it from: {{ com.maxprograms.fluenta.views.XmlPreferences}} and {{ com.maxprograms.fluenta.views.ProjectPreferences}}, and these 2 classes extend org.eclipse.swt.widgets.Composite.  These static methods are not related to the visual part and we do not use {{org.eclipse.swt}} in our projects, but thus we are forced to distribute swt.jar. 

Is it possible to use, for example, utility classes for these methods to separate the functional part from the visual part?

**Comment by rmraya** [comment]
Separating GUI from API is possible. Will try to make it on next release.

**Comment by AlexSmarandache15** [comment]
Hello,

Any update on this? Did you manage to work on it or is there a date when it could be ready?

If it helps, we could make the changes ourselves and send a pull request.

**Comment by rmraya** [comment]
Many changes were made to remove dependency on SWT from the command line interface and Java API. All changes are in current branch for version 3.0 and there is no estimated release date. It's too late to submit a pull request because the code has changed considerably.

**Comment by rmraya** [comment]
Code has changed for release 3.0. Provide a pull request against current code base if you want additional changes.
