### ISSUE TITLE
Exception "URI is not absolute" when generating an XLIFF for a project with a large ditamap

### ISSUE THREAD

**Issue by AlexSmarandache15** [rmraya/Fluenta#4]
Hello,

We are currently building an Oxygen XML Editor plugin that integrates Fluenta into the DITA Maps Manager. We are using {{com.maxprograms.fluenta.API}} for calling Fluenta operations.

I noticed that when we try to generate an XLIFF for somewhat larger ditamaps, an exception is thrown.
I also reproduced the problem with the original Fluenta application, version 2.5.0:
![image](https://user-images.githubusercontent.com/68815668/190597923-e08c5b81-c9a3-46e6-8b80-cb663f50f830.png)

I did not find useful information in the log (for example, what is the URI that is not absolute and triggered the exception).
The dita project on which I reproduce it is available on github: [https://github.com/oxygenxml/userguide](https://github.com/oxygenxml/userguide).

**Comment by rmraya** [comment]
This issue is fixed in current build of OpenXLIFF Filters. It is able to convert Oxygen's manual to XLIFF.
