### ISSUE TITLE
Restore the old System.err on finally on generateXliff

### ISSUE THREAD

**Issue by AlexSmarandache15** [rmraya/Fluenta#6]
Hello,

_System.err_ should be restored on a finally block because if an exception is thrown in the current code, the new PrintStream will remain set.

I put the link to the code here:
https://github.com/rmraya/Fluenta/blob/137b4449e89c9769c71b5d83294cc254381224e8/src/com/maxprograms/fluenta/controllers/LocalController.java#L438

**Comment by rmraya** [comment]
You are looking at old code.
