### ISSUE TITLE
Update H2 Database Engine to version 2.1.214 to reduce vulnerabilities

### ISSUE THREAD

**Issue by AlexJitianu** [rmraya/Fluenta#8]
Hello,

We are working to integrate Fluenta 3.0.0 into Oxygen "Fluenta DITA Translation" add-on. Fluenta uses the H2 Database Engine 1.4.200 which has 4 critical vulnerabilities reported:
https://mvnrepository.com/artifact/com.h2database/h2/1.4.200
They might not apply in the context in which Fluenta is using H2 (false positives), but it would be better to update H2 to version 2.1.214 in which 3 of those vulnerabilities have been resolved:
https://mvnrepository.com/artifact/com.h2database/h2/2.1.214
When we integrated Fluenta 2.6.0 we were able to bundle H2 2.1.214 and everything worked, but Fluenta 3.0.0 doesn't work with H2 2.1.214 out of the box. If we switch to 2.1.214 the actions to import/export TMX fail with errors like this:
```
\Fluenta-3.0.0>"C:\Program Files\Java\jdk-17.0.3.1\bin\java.exe" -cp "lib/h2-2.1.214.jar" --module-path jars -m fluenta/com.maxprograms.fluenta.Fluenta
Jan 03, 2023 1:23:12 PM com.maxprograms.swordfish.tm.InternalDatabase <init>
INFO: H2 database created
Jan 03, 2023 1:23:12 PM com.maxprograms.fluenta.views.MemoriesView exportTMX
SEVERE: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "TYPE_NAME" not found; SQL statement:
SELECT TYPE_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TUV' AND COLUMN_NAME='SEG' [42122-214]
```

**Comment by rmraya** [comment]
Vulnerabilities are known and don't apply in this context.

H2 will be upgraded in Fluenta after it is upgraded in [Swordfish](https://github.com/rmraya/Swordfish).
