### ISSUE TITLE
Mark shape element as translate=no

### ISSUE THREAD

**Issue by raducoravu** [rmraya/Fluenta#9]
Let's say I have a DITA topic with an image map:

           <imagemap id="gear_pump_map">
                    <image href="../images/Gear_pump_exploded.png" id="gear_pump_exploded">
                        <alt>Gear Pump</alt>
                    </image>
                    <area>
                        <shape>circle</shape>
                        <coords>172, 265, 14</coords>
                        <xref href="parts/bushings.dita#bushings_topic/bushings" format="dita"
                            >Bushings</xref>
                    </area>
                </imagemap>

That "shape" element has the default attribute translate=no specified in the DTD.

The following translation unit is generated:

    <trans-unit approved="no" id="9" xml:space="preserve">
      <source> <mrk ts="‹shape class=″+ topic/keyword ut-d/shape ″ translate=″no″​›" mtype="protected">circle</mrk> <mrk ts="‹coords class=″+ topic/ph ut-d/coords ″ translate=″no″​›" mtype="protected">172, 265, 14</mrk> <ph ctype="x-link" id="0">&lt;xref href="parts/bushings.dita#bushings_topic/bushings" class="- topic/xref " format="dita"&gt;</ph>Bushings<ph id="1">&lt;/xref&gt;</ph> </source>
        </trans-unit>

I think it should also have a translate=no attribute set on it.

**Comment by rmraya** [comment]
The "shape" element is properly set to protected. There is no need to mark the enclosing "trans-unit" element as untranslatable.

**Comment by raducoravu** [comment]
Thanks @rmraya I do not know xliff much. I was using this tool to translate the xliff for some tests and it seems to take into account the translate=no set on the trans-unit but it does not take that "mtype" into account and translated the text inside the shape to German:
https://smartcat.com/app
But probably this is a bug in the translation tool.

**Comment by rmraya** [comment]
It is indeed an issue in the translation tool, not a problem with Fluenta.
